name = "5minutes-call"
main = "src/index.ts" # ← ここは実際のエントリーポイントに合わせてください
compatibility_date = "2023-12-01"

# Workers開発用設定
workers_dev = true

# Durable Objectsの設定
[durable_objects]
bindings = [
  { name = "ROOM_SIGNALING", class_name = "RoomSignaling" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomSignaling"]

# 本番用環境の Durable Objects 設定
[env.production.durable_objects]
bindings = [
  { name = "ROOM_SIGNALING", class_name = "RoomSignaling" }
]

# ビルドコマンド（必要に応じて）
[build]
command = "npm run build"