name = "5minutes-call"
main = "workers/signaling.js"
compatibility_date = "2024-04-17"

[[durable_objects.bindings]]
name = "ROOM_SIGNALING"
class_name = "RoomSignaling"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RoomSignaling"]
