name = "5minutes-call"
main = "src/signaling.js"
compatibility_date = "2024-04-15"
workers_dev = true

[[durable_objects.bindings]]
name = "ROOM_SIGNALING"
class_name = "RoomSignaling"

[build]
upload.format = "modules"

[durable_objects]
bindings = [
  { name = "ROOM_SIGNALING", class_name = "RoomSignaling" }
]

[[migrations]]
tag = "v1"
new_classes = ["RoomSignaling"]
